apiVersion: batch/v1
kind: Job
metadata:
  name: optar-job
spec:
  template:
    metadata:
      labels:
        app: optar-job
    spec:
      serviceAccountName: optar-s3-cache-service-account
      containers:
      - name: optar
        image: DOCKER_IMAGE
      restartPolicy: Never
      backoffLimit: 3